### ISSUE TITLE
영어 번역 코드

### ISSUE THREAD

**Issue by min942773** [sejongresearch/EmojiRecommend#32]
파파고, 카카오 등은 글자 수 제한이 있어서 파이썬 라이브러리 사용
-> 구글에서 request가 한번에 많이 들어오면 IP를 일시적으로 차단하는 문제 발생
-> 약 3만개정도 되는 트윗을 300개씩 나눔 [파일은 여기로](https://drive.google.com/open?id=1hUPMA9tZl5D-B5xQKKD3_etzRG6GL1Sp)
-> 300개 실시 후 sleep으로 30분 쉬고 다시 실행되도록 코드를 작성함 [코드는 여기로](https://colab.research.google.com/drive/1_15pj3bOhsk6MghPrCrLsA9Fa3QxypgY)

- [x] 1~100
- [x] 100~110
- [x] 110~120
- [x] 120~130
- [x] 130~140
- [x] 140~150
- [x] 150~160
- [x] 160~170
- [x] 170~180
- [x] 180~190
- [x] 190~200
---
- [x] 200~210
- [x] 210~220
- [x] 220~230
- [x] 230~240
- [x] 240~250
- [x] 250~260
- [x] 260~270
- [x] 270~280
- [x] 280~290
- [x] 290~300
---
- [x] 300~310
- [x] 310~320
- [x] 320~330
- [x] 330~340
- [x] 340~350
- [x] 350~360
- [x] 360~370
- [x] 370~380
- [x] 380~390
- [x] 390~400
---
- [x] 400~410
- [x] 410~420
- [x] 420~430
- [x] 430~440
- [x] 440~450
- [x] 450~460
- [x] 460~470
- [x] 470~480
- [x] 480~490
- [x] 490~500

**Comment by min942773** [comment]
[번역코드.zip](https://github.com/hyj378/ArtificialIntelligence/files/3315395/default.zip)

**Comment by min942773** [comment]
[번역1.zip](https://github.com/hyj378/ArtificialIntelligence/files/3316709/1.zip)

**Comment by jiin0217** [comment]
[번역250-300.zip](https://github.com/hyj378/ArtificialIntelligence/files/3316736/250-300.zip)

**Comment by min942773** [comment]
[1~100.zip](https://github.com/hyj378/ArtificialIntelligence/files/3316737/1.100.zip)

**Comment by kimkyeongnam** [comment]
[100~121.zip](https://github.com/hyj378/ArtificialIntelligence/files/3316749/100.121.zip)

**Comment by hyj378** [comment]
[150-200.zip](https://github.com/hyj378/EmojiRecommand/files/3316830/150-200.zip)

**Comment by zero5two4** [comment]
[270~290.zip](https://github.com/hyj378/EmojiRecommand/files/3316926/270.290.zip)

**Comment by min942773** [comment]
[영어번역파일.zip](https://github.com/hyj378/EmojiRecommand/files/3316980/default.zip)
전체 영어 번역 파일입니다!!
