### ISSUE TITLE
영어 번역 데이터

### ISSUE THREAD

**Issue by min942773** [sejongresearch/EmojiRecommend#42]
각 감정 당 30000개, 총 150000개입니다.
[english_data.zip](https://github.com/hyj378/EmojiRecommand/files/3317104/english_data.zip)

**Comment by min942773** [comment]
[english_data_with_labels.zip](https://github.com/hyj378/EmojiRecommand/files/3317114/english_data_with_labels.zip)

**Comment by min942773** [comment]
[training_data.zip](https://github.com/hyj378/EmojiRecommand/files/3317162/training_data.zip)

**Comment by min942773** [comment]
[training_data2.zip](https://github.com/hyj378/EmojiRecommand/files/3317287/training_data2.zip)

**Comment by min942773** [comment]
[99,
 451,
 2226,
 2472,
 2606,
 2666,
 3546,
 3724,
 3776,
 4338,
 4626,
 6075,
 7056,
 9077,
 9298,
 9355,
 9379,
 9484,
 9643,
 9672,
 10668,
 11522,
 11953,
 11970,
 12349,
 12444,
 13091,
 13228,
 13339,
 13699,
 14157,
 14690,
 14832,
 15141,
 15260,
 15287,
 15341,
 15453,
 15563,
 15579,
 15732,
 15734,
 15791,
 15892,
 16006,
 16169,
 16261,
 16313,
 16501,
 16526,
 16618,
 16648,
 16740,
 16761,
 16918,
 16943,
 17027,
 17278,
 17310,
 17434,
 17571,
 17585,
 17595,
 17628,
 17808,
 17868,
 17884,
 17890,
 18022,
 18060,
 18139,
 18186,
 18202,
 18265,
 18371,
 18389,
 18474,
 18522,
 18666,
 18738,
 18773,
 18788,
 18794,
 18868,
 18986,
 18993,
 19041,
 19085,
 19162,
 19239,
 19324,
 19368,
 19380,
 19620,
 19645,
 19741,
 19832,
 19931,
 20065,
 20240,
 20257,
 20427,
 20447,
 20462,
 20472,
 20473,
 20578,
 20626,
 20700,
 20812,
 20891,
 20907,
 20975,
 20977,
 20994,
 21076,
 21094,
 21125,
 21162,
 21406,
 21417,
 21436,
 21513,
 21589,
 21594,
 21603,
 21645,
 21721,
 21767,
 21782,
 21803,
 21823,
 21891,
 21996,
 21999,
 22060,
 22192,
 22203,
 22257,
 22615,
 22627,
 22702,
 22715,
 22881,
 22899,
 22977,
 23085,
 23091,
 23100,
 23190,
 23257,
 23334,
 23403,
 23416,
 23540,
 23574,
 23719,
 23737,
 23776,
 23825,
 23845,
 23852,
 23989,
 24052,
 24072,
 24155,
 24262,
 24275,
 24296,
 24376,
 24468,
 24476,
 24514,
 24540,
 24590,
 24623,
 24677,
 24730,
 24828,
 24839,
 24864,
 25017,
 25106,
 25137,
 25168,
 25175,
 25281,
 25313,
 25386,
 25421,
 25459,
 25461,
 25463,
 25551,
 25622,
 25624,
 25739,
 25812,
 25850,
 25859,
 26001,
 26055,
 26110,
 26113,
 26168,
 26171,
 26301,
 26373,
 26410,
 26436,
 26705,
 26857,
 26913,
 26982,
 26994,
 27058,
 27146,
 27166,
 27260,
 27265,
 27331,
 27483,
 27489,
 27505,
 27543,
 27552,
 27590,
 27627,
 27651,
 27654,
 28004,
 28140,
 28338,
 28445,
 28597,
 28598,
 28619,
 28673,
 28893,
 28918,
 28931,
 28965,
 29173,
 29258,
 29363,
 29370,
 29447,
 29567,
 29579,
 29748,
 29830,
 29871,
 29878,
 29882,
 31287,
 31532,
 32873,
 32915,
 32920,
 33504,
 34483,
 34496,
 34795,
 34816,
 35348,
 35404,
 35497,
 35560,
 35785,
 35943,
 36844,
 37399,
 37736,
 37754,
 38586,
 38625,
 38991,
 39341,
 39533,
 39867,
 40053,
 40401,
 40423,
 40552,
 41327,
 42426,
 43567,
 44240,
 44738,
 45437,
 45818,
 46309,
 46443,
 46599,
 46606,
 46784,
 46976,
 47007,
 47410,
 47540,
 47577,
 47621,
 47955,
 48827,
 48989,
 49646,
 49892,
 50038,
 51050,
 51337,
 51400,
 51515,
 51771,
 51946,
 52463,
 52846,
 53268,
 53597,
 53829,
 54337,
 54453,
 54578,
 54852,
 55016,
 55085,
 55236,
 55551,
 55660,
 55747,
 55882,
 56373,
 56377,
 56727,
 57143,
 57146,
 57460,
 58432,
 58526,
 58570,
 58589,
 58742,
 58975,
 59002,
 59211,
 59604,
 59617,
 59934,
 59988,
 62770,
 63424,
 65265,
 65806,
 67232,
 71057]

**Comment by kimkyeongnam** [comment]
### 900*5=4500개 파일
[training_data3.zip](https://github.com/hyj378/EmojiRecommand/files/3317581/training_data3.zip)

**Comment by kimkyeongnam** [comment]
# 600*5=3000개 파일
* 통합본
[training_data4.zip](https://github.com/hyj378/EmojiRecommand/files/3317700/training_data4.zip)

* 나눠진거
[seperate.zip](https://github.com/hyj378/EmojiRecommand/files/3317699/seperate.zip)

* 코드
[Dataframe Merge & Find nan.zip](https://github.com/hyj378/EmojiRecommand/files/3317701/Dataframe.Merge.Find.nan.zip)

**Comment by kimkyeongnam** [comment]
### 300*5=1500개 파일
* 통합본
[training_data5.zip](https://github.com/hyj378/EmojiRecommand/files/3317703/training_data5.zip)

* 코드
[Dataframe Merge & Find nan.zip](https://github.com/hyj378/EmojiRecommand/files/3317704/Dataframe.Merge.Find.nan.zip)

* 결측값
[441, 560, 587]

**Comment by hyj378** [comment]
[fear_english300.zip](https://github.com/hyj378/EmojiRecommand/files/3317791/fear_english300.zip)

**Comment by min942773** [comment]
[label1, 2.zip](https://github.com/hyj378/EmojiRecommand/files/3317793/label1.2.zip)

**Comment by kimkyeongnam** [comment]
[label 5.zip](https://github.com/hyj378/EmojiRecommand/files/3317795/label.5.zip)

**Comment by min942773** [comment]
[happy_label300.zip](https://github.com/hyj378/EmojiRecommand/files/3317874/happy_label300.zip)

**Comment by min942773** [comment]
[300training_data.zip](https://github.com/hyj378/EmojiRecommand/files/3317883/300training_data.zip)

**Comment by kimkyeongnam** [comment]
유진아 이걸로 돌려봐용
[NN Model.zip](https://github.com/hyj378/EmojiRecommand/files/3317913/NN.Model.zip)

**Comment by min942773** [comment]
[주혁오빠꺼.zip](https://github.com/hyj378/EmojiRecommand/files/3317935/default.zip)

**Comment by min942773** [comment]
[[텀프로젝트] 이모티콘 분류 논문.pdf](https://github.com/sejongresearch/EmojiRecommand/files/3318004/default.pdf)
